### ISSUE TITLE
Process Kill

### ISSUE THREAD

**Issue by 00013786** [00013786/edr_solution#2]
There is a bug with process kill function, there should be prompt or check function that should check and tell if this function truly deleted or not

**Comment by 00013786** [comment]
Latest update should fix the problem

**Comment by mashiachilov** [comment]
latest update did not fix that, there is a problem in server side where process id cannot be located. Suppose to be an easy fix
